Размечает главную страницу
htmlacademy-adaptive/1123257-pink-24 pull request #2
Opened 2021-11-29 19:04 UTC by Vkhv73

2021-11-30 10:53 UTC, PavelNyukalo requested changes

2021-11-30 10:53 UTC, PavelNyukalo commented on source/index.html
> +    </a>
Ошибка по методологии - модификатор не может использоваться в отрыве от модифицируемой сущности, (`page-logo page-logo--header`), это раз, во-вторых тут больше подойдет элемент от блока `page-header`, например `page-header__logo`. И с картинкой соответственно так же, но ей можно пока не давать класс

2021-11-30 10:53 UTC, PavelNyukalo commented on source/index.html
> +          <li class="user-list__item user-list__item--current">
Вот как здесь, здесь правильно, сначала сущность, потом ее модификатор `user-list__item user-list__item--current`

2021-11-30 10:53 UTC, PavelNyukalo commented on source/index.html
> +    </div>
Я думаю тут можно отдельный блок выделить - `intro` и уже от него называть элементы

2021-11-30 10:53 UTC, PavelNyukalo commented on source/index.html
> +        <span class="dialogue-offer">Нам есть, что вам предложить!</span>
`dialogue-question` и `dialogue-offer` получаются отдельными блоками - то есть им надо будет делать отдельный стилевой файл. Предлагаю может разбить их на два элемента `information__title` и `information__offer`

2021-11-30 10:53 UTC, PavelNyukalo commented on source/index.html
> +        </li>
Такая же проблема с модификатором.
Тут есть два решения:
1. Сделать `li` отдельным блоком, и уже задавать от этого `li` - `item__title` и тд
2. Либо просто назвать их `information__item-title` и тд

Плюс тут нарушается вложенность заголовков, `h2` у нас идет выше, тут уже более уместно `h3`

2021-11-30 10:53 UTC, PavelNyukalo commented on source/index.html
> +          </div>
`information__item--photo-item` - модификатор без сущности.
Можно сделать отдельным блоком, будет `information__photo-list photo-list`. И уже фотки будут `photo-list__item`

2021-11-30 10:53 UTC, PavelNyukalo commented on source/index.html
> +        </div>
Можно же не оборачивать ссылки в `div`, тогда и код чище и с классами легче будет

2021-11-30 10:53 UTC, PavelNyukalo commented on source/index.html
> +      </div>
Тут тоже можно не оборачивать

2021-11-30 12:14 UTC, Vkhv73 commented on source/index.html
> +    </a>
+

2021-11-30 12:15 UTC, Vkhv73 commented on source/index.html
> +          <li class="user-list__item user-list__item--current">
+

2021-11-30 12:27 UTC, Vkhv73 commented on source/index.html
> +    </div>
+?

2021-11-30 12:32 UTC, Vkhv73 commented on source/index.html
> +        <span class="dialogue-offer">Нам есть, что вам предложить!</span>
+?

2021-11-30 12:32 UTC, Vkhv73 commented on source/index.html
> +        </li>
+?

2021-11-30 12:41 UTC, Vkhv73 commented on source/index.html
> +          </div>
+?

2021-11-30 12:43 UTC, Vkhv73 commented on source/index.html
> +        </div>
+??

2021-11-30 12:46 UTC, Vkhv73 commented on source/index.html
> +      </div>
++

2021-12-01 06:59 UTC, PavelNyukalo requested changes

2021-12-01 06:59 UTC, PavelNyukalo commented on source/index.html
> +          <h2 class="information__item-title">
Тут забыл исправить на `h3`, `h2` у нас выше "Устали от серости мегаполиса?".
Кстати, может быть убрать скрытый заголовок, а `information__title` сделать как раз-таки заголовком, поскольку они дублируют друг друга. А `information__offer` тоже тогда можно вынести и получится что-то типа такого:
```html
<section>
  h2.information__title Устали...
  p.information__offer Нам есть...
  ul.information__list
```

2021-12-01 06:59 UTC, PavelNyukalo commented on source/index.html
> +      </div>
`information__photo-list-title` можно удалить, поскольку заголовок у нас скроется, стилизовать мы его никак не будем. А `div` `information__item information__item--photo-list` можно убрать, он выглядит лишним

2021-12-01 10:23 UTC, Vkhv73 commented on source/index.html
> +          <h2 class="information__item-title">
пока переделал на h3.

2021-12-01 10:23 UTC, Vkhv73 commented on source/index.html
> +      </div>
убрал div

2021-12-01 10:29 UTC, PavelNyukalo approved these changes

2021-12-01 10:29 UTC, merged