Верстает каталог и форму
htmlacademy-adaptive/1123257-pink-24 pull request #3
Opened 2021-12-01 11:43 UTC by Vkhv73

2021-12-02 05:39 UTC, PavelNyukalo requested changes

2021-12-02 05:39 UTC, PavelNyukalo commented on source/catalog.html
> +        </p>
Если текст скрытого заголовка дублируется с другими элементами, то можно не добавлять скрытый, а сделать сразу заголовок `h1` видимым

2021-12-02 05:39 UTC, PavelNyukalo commented on source/catalog.html
> +          </li>
Предлагаю карточки фоток сделать отдельным бэм-блоком, чтобы как минимум избавиться от названий `catalog__item-photo catalog__item-photo-photo`.
И названия будут чище, например на `li` повесить `catalog__item photo-card`. И у тебя уже будут `photo-card__sticker`, photo-card__author`, photo-card__description` и тд

2021-12-02 05:39 UTC, PavelNyukalo commented on source/catalog.html
> +            <input type="range" min="0" max="100" step="1" value="50">
Насчет `radio`, для мобильной версии вполне себе решение, но на планшете и больше там уже все три показываются и все три доступны, так что думаю тут лучше просто кнопками теми же сделать

2021-12-02 08:58 UTC, Vkhv73 commented on source/catalog.html
> +        </p>
Пока переименовал только содержание заголовка h1.

2021-12-02 11:21 UTC, Vkhv73 commented on source/catalog.html
> +            <input type="range" min="0" max="100" step="1" value="50">
поправил, но кнопкам пока не навесил классы..

2021-12-02 11:22 UTC, Vkhv73 commented on source/catalog.html
> +          </li>
исправил.

2021-12-03 16:32 UTC, PavelNyukalo approved these changes

2021-12-03 16:34 UTC, merged